databases:
  - name: foodrecipe
    databaseName: foodrecipe
    user: foodrecipe_user

services:
  - type: web
    name: Food
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodrecipe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false